
services:
  # 1. Controller/Load Balancer Service
  controller:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - api

  # 2. API Service (Lumen/Laravel)
  api:
    build:
      context: ./backend  # Dati ./api, gawin nating ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www # Dati ./api, gawin nating ./backend
    depends_on:
      - database
      - searcher

  # 3. Database Service (Relational)
  database:
    image: mysql:8.0 # Pwedeng PostgreSQL depende sa gamit mo
    environment:
      MYSQL_DATABASE: crm_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  # 4. Searcher Service (Elasticsearch)
  searcher:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"